import { useNavigate } from 'react-router-dom'
import { useData } from '../context/DataContext'
import { eisenhowerTone, formatDate, movideskTicketUrl, priorityTone, riskTone, slaTone, statusTone } from '../utils/tickets'

export function ticketSummary(ticket) {
  return `Ticket #${ticket.numero}\nAssunto: ${ticket.assunto}\nStatus original: ${ticket.status}\nStatus gerencial: ${ticket.statusGerencial}\nTipo ITIL: ${ticket.tipoITIL}\nPrioridade gerencial: ${ticket.prioridadeGerencial}\nNível de risco: ${ticket.nivelRisco}\nScore de risco: ${ticket.scoreRisco}\nSLA: ${ticket.situacaoSLA} (${ticket.slaDiasReferencia ?? '—'} dias)\nQuadrante Eisenhower: ${ticket.quadranteEisenhower}\nUrgente: ${ticket.urgente ? 'Sim' : 'Não'}\nImportante: ${ticket.importante ? 'Sim' : 'Não'}\nMotivos de urgência: ${(ticket.motivoUrgencia || []).join(', ') || 'Nenhum'}\nMotivos de importância: ${(ticket.motivoImportancia || []).join(', ') || 'Nenhum'}\nAção recomendada: ${ticket.acaoRecomendada}\nPeso Pareto: ${ticket.pesoPareto}\nCliente: ${ticket.clientePessoa}\nDepartamento: ${ticket.departamento}\nResponsável: ${ticket.responsavel}\nTempo em aberto: ${ticket.tempoEmAbertoDias} dias\nTempo sem atualização: ${ticket.tempoSemAtualizacaoDias} dias\nResponsável gerencial: ${ticket.responsavelGerencial}\nDependência externa: ${ticket.dependenciaExterna ? 'Sim' : 'Não'}\nMotivo de espera: ${ticket.motivoEsperaInferido}\nAlertas de qualidade: ${(ticket.qualidadeDados || []).join(', ') || 'Nenhum'}`
}

export default function TicketModal({ ticket, onClose }) {
  const navigate = useNavigate()
  const { setMessage } = useData()
  if (!ticket) return null
  const copy = async () => {
    try { await navigator.clipboard.writeText(ticketSummary(ticket)); setMessage({ type: 'success', text: 'Resumo copiado.' }) }
    catch { setMessage({ type: 'error', text: 'O navegador não permitiu copiar o resumo.' }) }
  }
  const fields = [
    ['Número', `#${ticket.numero}`], ['Status', ticket.status], ['Dias em aberto', `${ticket.tempoEmAbertoDias} dias`],
    ['Departamento', ticket.departamento], ['Usuário solicitante', ticket.usuarioSolicitante], ['Cliente', ticket.clientePessoa],
    ['Serviço', ticket.servico], ['Responsável', ticket.responsavel], ['Categoria', ticket.categoria],
    ['Aberto em', formatDate(ticket.abertoEm)], ['Última ação', formatDate(ticket.ultimaAcao)], ['Ticket priorizado', ticket.ticketPriorizado ? 'Sim' : 'Não']
  ]
  const governance = [
    ['Status gerencial', ticket.statusGerencial], ['Tipo ITIL', ticket.tipoITIL], ['Impacto estimado', ticket.impactoEstimado],
    ['Urgência estimada', ticket.urgenciaEstimada], ['Tempo sem atualização', `${ticket.tempoSemAtualizacaoDias} dias`],
    ['Responsável gerencial', ticket.responsavelGerencial], ['Dependência externa', ticket.dependenciaExterna ? 'Sim' : 'Não'],
    ['Motivo de espera', ticket.motivoEsperaInferido], ['SLA de referência', `${ticket.slaDiasReferencia ?? '—'} dias`]
  ]
  return <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={onClose}><div className="card w-full max-w-3xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-brand">Ticket #{ticket.numero}</p><h2 className="mt-2 text-xl font-extrabold">{ticket.assunto}</h2></div><button className="text-3xl text-muted" onClick={onClose}>×</button></div><span className={`badge mt-4 ${statusTone(ticket.status)}`}>{ticket.status}</span><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-[10px] font-bold uppercase text-muted">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value}</p></div>)}</div>
    <section className="mt-5 rounded-2xl border border-indigo-200 bg-indigo-50/50 p-4 dark:border-slate-700 dark:bg-slate-800/60"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Governança</h3><p className="mt-1 text-[11px] text-muted">Informações inferidas automaticamente pelo sistema; não alteram o Excel.</p></div><div className="flex flex-wrap gap-2"><span className={`badge ${priorityTone(ticket.prioridadeGerencial)}`}>{ticket.prioridadeGerencial}</span><span className={`badge ${riskTone(ticket.nivelRisco)}`}>{ticket.nivelRisco} · {ticket.scoreRisco}</span><span className={`badge ${slaTone(ticket.situacaoSLA)}`}>{ticket.situacaoSLA}</span></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{governance.map(([label, value]) => <div key={label}><p className="text-[10px] font-bold uppercase text-muted">{label}</p><p className="mt-1 break-words text-xs font-semibold">{value}</p></div>)}</div><div className="mt-4 border-t pt-3"><p className="text-[10px] font-bold uppercase text-muted">Alertas de qualidade</p><div className="mt-2 flex flex-wrap gap-1.5">{ticket.qualidadeDados?.length ? ticket.qualidadeDados.map((alert) => <span key={alert} className="badge bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300">{alert}</span>) : <span className="badge bg-emerald-100 text-emerald-700">Sem alertas</span>}</div></div></section>
    <section className="mt-5 rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Priorização gerencial</h3><p className="mt-1 text-[11px] text-muted">Eisenhower combina urgência e importância; Pareto reforça os grupos de maior concentração.</p></div><span className={`badge ${eisenhowerTone(ticket.quadranteEisenhower)}`}>{ticket.quadranteEisenhower}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-[10px] font-bold uppercase text-muted">Urgente: {ticket.urgente ? 'Sim' : 'Não'}</p><ul className="mt-2 space-y-1 text-xs">{ticket.motivoUrgencia?.length ? ticket.motivoUrgencia.map((reason) => <li key={reason}>• {reason}</li>) : <li className="text-muted">• Nenhum motivo identificado</li>}</ul></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-[10px] font-bold uppercase text-muted">Importante: {ticket.importante ? 'Sim' : 'Não'}</p><ul className="mt-2 space-y-1 text-xs">{ticket.motivoImportancia?.length ? ticket.motivoImportancia.map((reason) => <li key={reason}>• {reason}</li>) : <li className="text-muted">• Nenhum motivo identificado</li>}</ul></div></div><div className="mt-3 rounded-xl bg-blue-50 p-3 text-xs leading-5 dark:bg-blue-950/50"><strong>Ação recomendada:</strong> {ticket.acaoRecomendada}</div><div className="mt-3 flex flex-wrap gap-2"><span className="badge bg-violet/15 text-purple-700">Peso Pareto: {ticket.pesoPareto}</span><span className="badge bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-200">Grupo principal: {ticket.grupoParetoPrincipal}</span></div></section>
    <div className="mt-6 flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={copy}>Copiar resumo</button><button className="btn-secondary" onClick={() => navigate(`/ticket?numero=${encodeURIComponent(ticket.numero)}`)}>Abrir na aba Ticket</button><a className="btn-primary" href={movideskTicketUrl(ticket.numero)} target="_blank" rel="noreferrer">Ver no Movidesk ↗</a></div></div></div>
}
